# Different user sessions should share an unique ssh-agent.
if [ -e $HOME/.ssh-agent ] && [ `ps -au$USER | grep ssh-agent | wc -l` != 0 ]; then
  SSH_AUTH_SOCK=$HOME/.ssh-agent
  SSH_AGENT_PID=`ps -au$USER -eo pid,comm | grep ssh-agent | head -n1 | awk '{ print $1 }'`
  export SSH_AUTH_SOCK SSH_AGENT_PID
fi


[ -e $HOME/.ssh-agent ] || eval `ssh-agent -a $HOME/.ssh-agent` &> /dev/null

# tty1 is allocated for X, further allocations correspond for a shell session.
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec xinit
else
  exec zellij
fi
