if [ ! -z $TERMUX_VERSION ] && [ `pgrep gpg-agent | wc -l` = 0 ]; then
  eval `gpg-agent --daemon --enable-ssh-support`
elif [ ! -z $TERMUX_VERSION ]; then
  export SSH_AUTH_SOCK=`gpgconf --list-dirs agent-ssh-socket`
fi

[ ! -z $TERMUX_VERSION ] && return

# systemd doesn't setup environment variables for new sessions
if [ `systemctl --user is-active ssh-agent` = "active" ]; then
  eval `systemctl --user show ssh-agent --property Environment --value`
  SSH_AGENT_PID=`systemctl --user show ssh-agent --property MainPID --value`
elif [ `systemctl --user is-active gpg-agent-ssh.socket` = "active" ]; then
  SSH_AUTH_SOCK=`gpgconf --list-dirs agent-ssh-socket`
fi

export SSH_A{UTH_SOCK,GENT_PID}

# tty1 is allocated for X, further allocations correspond for a shell session.
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec xinit
else
  exec zellij
fi
